/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// ImageMessageEvent 图片消息事件
type ImageMessageEvent struct {
	ToUserName   string `json:"toUserName,omitempty"`
	FromUserName string `json:"fromUserName,omitempty"`
	CreateTime   int64  `json:"createTime,omitempty"`
	MsgType      string `json:"msgType,omitempty"`
	MsgId        int64  `json:"msgId,omitempty"`
	PicUrl       string `json:"picUrl,omitempty"`
	MediaId      string `json:"mediaId,omitempty"`
	MediaURL     string `json:"mediaURL,omitempty"`
}
