/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// VoiceMessage 语音消息
type VoiceMessage struct {
	MediaId string `json:"mediaId,omitempty"`
	// 音频链接
	MediaURL string `json:"mediaURL,omitempty"`
}
