/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// EventsEvent 链接消息事件
type EventsEvent struct {
	ToUserName   string  `json:"toUserName,omitempty"`
	FromUserName string  `json:"fromUserName,omitempty"`
	CreateTime   int64   `json:"createTime,omitempty"`
	MsgType      string  `json:"msgType,omitempty"`
	Event        string  `json:"event,omitempty"`
	EventKey     string  `json:"eventKey,omitempty"`
	Ticket       string  `json:"ticket,omitempty"`
	Latitude     float64 `json:"latitude,omitempty"`
	Longitude    float64 `json:"longitude,omitempty"`
	Precision    float64 `json:"precision,omitempty"`
}
