/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// ImageMessage 图片消息
type ImageMessage struct {
	MediaId string `json:"mediaId,omitempty"`
	// 图片链接
	MediaURL string `json:"mediaURL,omitempty"`
}
