/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// LocationMessageEvent 地理位置消息事件
type LocationMessageEvent struct {
	ToUserName   string  `json:"toUserName,omitempty"`
	FromUserName string  `json:"fromUserName,omitempty"`
	CreateTime   int64   `json:"createTime,omitempty"`
	MsgType      string  `json:"msgType,omitempty"`
	MsgId        int64   `json:"msgId,omitempty"`
	LocationX    float64 `json:"locationX,omitempty"`
	LocationY    float64 `json:"locationY,omitempty"`
	Scale        int32   `json:"scale,omitempty"`
	Label        string  `json:"label,omitempty"`
}
