/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// TextMessage 文本消息
type TextMessage struct {
	// 文本内容
	Content string `json:"content,omitempty"`
}
