/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// UserTag 用户标签
type UserTag struct {
	// 公众平台标签id
	Id int64 `json:"id,omitempty"`
	// 标签名称
	Name string `json:"name,omitempty"`
}
