/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// ListUserReq struct for ListUserReq
type ListUserReq struct {
	// 公众号id
	Id string `json:"id,omitempty"`
}
