/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// ArticlesMessage 图文消息
type ArticlesMessage struct {
	// 标题
	Title string `json:"title,omitempty"`
	// 描述
	Description string `json:"description,omitempty"`
	// 链接
	URL string `json:"URL,omitempty"`
	// 图片链接
	PicURL string `json:"picURL,omitempty"`
}
