/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// SendMessageReq struct for SendMessageReq
type SendMessageReq struct {
	// 发送人(运营号Id)
	FromUser string `json:"fromUser,omitempty"`
	// 接收用户openid
	ToUser string `json:"toUser,omitempty"`
	// 消息类型:text 文本,image 图片,video 视频,voice 音频,music 音乐,articles 新闻
	MsgType  string          `json:"msgType,omitempty"`
	Text     TextMessage     `json:"text,omitempty"`
	Image    ImageMessage    `json:"image,omitempty"`
	Voice    VoiceMessage    `json:"voice,omitempty"`
	Video    VideoMessage    `json:"video,omitempty"`
	Music    MusicMessage    `json:"music,omitempty"`
	Articles ArticlesMessage `json:"articles,omitempty"`
}
