/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// MusicMessage 音乐消息
type MusicMessage struct {
	// 音乐标题
	Title string `json:"title,omitempty"`
	// 音乐描述
	Description string `json:"description,omitempty"`
	// 音乐链接
	MusicURL string `json:"musicURL,omitempty"`
	// 高品质音乐链接，wifi环境优先使用该链接播放音乐
	HqmusicURL   string `json:"hqmusicURL,omitempty"`
	ThumbMediaId string `json:"thumbMediaId,omitempty"`
	// 音乐图片链接
	ThumbMediaURL string `json:"thumbMediaURL,omitempty"`
}
