/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// TextMessageEvent 文本消息事件
type TextMessageEvent struct {
	// 开发者微信号
	ToUserName string `json:"toUserName,omitempty"`
	// 发送方微信号，若为普通用户，则是一个OpenID
	FromUserName string `json:"fromUserName,omitempty"`
	CreateTime   int64  `json:"createTime,omitempty"`
	Content      string `json:"content,omitempty"`
	MsgType      string `json:"msgType,omitempty"`
	// 消息id
	MsgId int64 `json:"msgId,omitempty"`
}
