/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// UpdateUserTagReq struct for UpdateUserTagReq
type UpdateUserTagReq struct {
	// 公众号id
	Id string `json:"id,omitempty"`
	// 用户openid
	Openid string `json:"openid,omitempty"`
	// 标签列表
	Tags []string `json:"tags,omitempty"`
}
