/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// VoiceMessageEvent 语音消息事件
type VoiceMessageEvent struct {
	ToUserName   string `json:"toUserName,omitempty"`
	FromUserName string `json:"fromUserName,omitempty"`
	CreateTime   int64  `json:"createTime,omitempty"`
	MsgType      string `json:"msgType,omitempty"`
	MsgId        int64  `json:"msgId,omitempty"`
	Format       string `json:"format,omitempty"`
	MediaId      string `json:"mediaId,omitempty"`
	MediaURL     string `json:"mediaURL,omitempty"`
	Recognition  string `json:"recognition,omitempty"`
}
