/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// UserDetailReq struct for UserDetailReq
type UserDetailReq struct {
	// 公众号id
	Id string `json:"id,omitempty"`
	// 用户openid
	Openid string `json:"openid,omitempty"`
}
