/*
 * Uim mp api
 *
 * uim mp api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wpub

// VideoMessage 视频消息
type VideoMessage struct {
	MediaId      string `json:"mediaId,omitempty"`
	ThumbMediaId string `json:"thumbMediaId,omitempty"`
	// 视频链接
	MediaURL string `json:"mediaURL,omitempty"`
	// 视频封面图片链接
	ThumbMediaURL string `json:"thumbMediaURL,omitempty"`
	// 视频标题
	Title string `json:"title,omitempty"`
	// 视频描述
	Description string `json:"description,omitempty"`
}
